### ISSUE TITLE
SidebarIconの実装について

### ISSUE THREAD

**Issue by mizushima1226** [iwkt/react-sidebar#2]
SidebarIconコンポーネントにて、
`className="SidebarIcon"`
のクラス名を指定しているかと思います
このクラスに対するスタイリングはSidebar.jsxで行われています

プレーンなHTML/CSSではCSSの定義はグローバルに反映されますが、
ReactでのCSSはコンポーネントに閉じたCSSを適用できるメリットがあります

ので、Sidebarで定義している`.SidebarIcon`のCSSは`SidebarIcon.jsx`側に持たせてあげるとより良い実装になります👍
```
.SidebarIcon {
    padding-top: 20px;
    padding-bottom: 15px;
    text-align: center;
    & img {
      width: 100px;
      height: 100px;
    }
    & p {
      color: white;
      font-weight: 600;
      font-size: 13px;
    }
  }
```

**Comment by iwkt** [comment]
Iconに関するcssをSidebar.jsxからSidebarIcon.jsxに移設しました。

**Comment by mizushima1226** [comment]
確認できました👍
