### ISSUE TITLE
CSSのidの適用について

### ISSUE THREAD

**Issue by mizushima1226** [iwkt/react-sidebar#3]
```
 <li
  key={key}
  className="row"
  onClick={() => {
    window.location.pathname = value.link;
  }}
  id={window.location.pathname == value.link ? 'active' : ''}
>
  <div id="icon">{value.icon}</div>
  <div id="title">{value.title}</div>
</li>
```

id指定している箇所ですが、map関数で複数アイテムがレンダリングされるので、同一のidが複数存在することになってしまいます
idは１画面で一意となるルールになっているのでクラス指定するのが良さそうです💡

今回のルール違反は特に悪影響ないですが、JSでidを指定してDOMを取得する時など、想定と違う挙動するのでデバッグが大変になります〜

**Comment by iwkt** [comment]
質問です。以下の部分もclassの方が良いでしょうか。

id={window.location.pathname == value.link ? 'active' : ''

ハンドリングが面倒になりそうなのでidを使ってしまいました。
おっしゃる通りmapでidがいくつかできてしまいます。id=''みたいなものもやっぱりNGでしょうか。

  <div id="icon">{value.icon}</div>
  <div id="title">{value.title}</div>
に関してはclassにしました。

よろしくお願いしま〜す。

**Comment by mizushima1226** [comment]
`active`という命名をするならclassの方が良さそうですね👀
だいぶ抽象的な命名なので、他にも一覧表示するような画面があったときに`active`と命名するパターンは出てきそうだなぁと思いました

idの命名だけでやりくりしようとすると、`sidebar-item_active`など、命名規則で頑張る感じになりそうですね🤔

**Comment by mizushima1226** [comment]
icon/titleの件、確認しました！

このissueとは話題が少し逸れますが、
https://styled-components.com/docs/basics#passed-props
のようにstyled componentsに対してpropsを渡すことができます

サンプルコード引用（クラスコンポーネントの書き方でrenderメソッドありますが気にしなくてOK）
```
// Create an Input component that'll render an <input> tag with some styles
const Input = styled.input`
  padding: 0.5em;
  margin: 0.5em;
  color: ${props => props.inputColor || "palevioletred"};
  background: papayawhip;
  border: none;
  border-radius: 3px;
`;

// Render a styled text input with the standard input color, and one with a custom input color
render(
  <div>
    <Input defaultValue="@probablyup" type="text" />
    <Input defaultValue="@geelen" type="text" inputColor="rebeccapurple" />
  </div>
);
```

こんな感じで受け取ったpropsで`color`の値を出しわけすることができます

同じ要領でpropsで`isActive`のようなbooleanを渡し、styled components側で
isActiveならばbackground-colorを指定する
と言った実装ができます（こちらの方がよりReact的な実装ですね〜）

styled components使っていく上ではよくやることなので、そもそもの今回の課題のところでいくと、ややアドバンスドな感じになりますがstyled componentsの練習にはちょうど良いかと💡
やるやらない、はお任せします〜（他のライブラリの方もあると思うので）

**Comment by iwkt** [comment]
あーなるほど、そうですね。
トライしてみまｓ。

**Comment by iwkt** [comment]
Tryしましたがさっぱりわかりませんでした。
別に下記のように試験用ファイルを作りためしてみました。
やりたいことはクリックした<li>に対してcolor={active}をtrueにしたりfalseにしたりということ。
この判定によりstyled-componets 中のcolor: ${(props) => (props.color ? "blue" : "red")};で色を出し分けしたい。


試験用ファイル
```
import styled from "styled-components";
import { useState } from "react";

const Data = [
  {
    name: "Taro",
    sex: "m"
  },
  {
    name: "Hana",
    sex: "f"
  },
  {
    name: "Gori",
    sex: "m"
  }
];

export const Test = () => {
  const [active, setActive] = useState(false);
  const colorToggle = (index) => {　// <- ここの書き方がわからず。indexを活かせていない
    setActive(!active);
  };
  return (
    <>
      <ul>
        {Data.map((value, index) => {
          return (
            <StyledHello
              key={index}
              color={active}
              onClick={() => colorToggle(index)} // <- ここで何行目がクリックされたか取得
            >
              {value.name}
            </StyledHello>
          );
        })}
      </ul>
    </>
  );
};

const StyledHello = styled.li`
  cursor: pointer;
  user-select: none;
  color: ${(props) => (props.color ? "blue" : "red")};

`;
```

やったこと：
liタグを取得して属性を書き換えるのようなこと(下code参照)もしたが全くダメです。

```
const Li = document.getElementsByTagName("li");
let atr = Li[index].getAttribute("color");
atr = "isActive";
```

もう、５〜６時間やってます。限界です。
そもそもの考え方が間違っているのかどうなのか？
なにかヒントをください泣

**Comment by mizushima1226** [comment]
上記コードを見る限りだと、クリック時に全てのli要素が青になったり赤になったりという挙動でしょうか？
`StyledHello`コンポーネントは正しく書けているように見えます👀
`StyledHello`のcolorの出し分けがうまくできていれば第一段階はOKかなと！

```
const colorToggle = (index) => {　// <- ここの書き方がわからず。indexを活かせていない
    setActive(!active);
  };
```

このように引数で指定したindexに対応する要素に対してステートを変更したい、となると
１つのactiveステートだけでは賄い切れないかと🤔
`Data`配列の各要素にactiveプロパティを持たせ、ステート管理しないと実現できなさそうです💡

**Comment by iwkt** [comment]
はい、li要素が全て色が変わって異しまうと言う状態です。個別に色の出し入れをしたかったわけです。
Dataの方にactiiveプロパティ。あーなるほど。下記のようなことですね。

```
const Data = [
  {
    name: "Taro",
    sex: "m",
    isActive: false
  },
  {
    name: "Hana",
    sex: "f",
    isActive: false
  },
  {
    name: "Gori",
    sex: "m",
    isActive: false
  }
];
```

第一段階はOKということでとりあえずここまでにしておき先へ進みます。
ありがとうございました。

**Comment by mizushima1226** [comment]
認識あっております〜🙌
issueはcloseします〜〜
