### ISSUE TITLE
クラス名の命名規則について

### ISSUE THREAD

**Issue by mizushima1226** [iwkt/react-sidebar#4]
```
<div className="Sidebar">
```
などクラス名にパスカルケースを用いてる箇所がいくつか見受けられます
キャメルケースと混ざっているのでどちらかに統一しておくと良さそうです👍

**Comment by iwkt** [comment]
こちらキャメルケースに統一しました。
有難うございました。

**Comment by mizushima1226** [comment]
修正内容確認しました〜 7c74b615f024ee48f9a524905933c94ca3188f99
`SidebarIcon`だけパスカルのままでしたので、修正後こちらのissueはcloseしていただいてOKです🙆‍♂️

**Comment by iwkt** [comment]
すいません。取りこぼしていました。修正しましたのでcloseします。
